version: "3.9"
services:
  roasbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      # coloque seu(s) token(s) de ingest aqui
      INGEST_TOKENS: "ce3de8ddd3466f59f084b2e9b2ef2a359c5f43903eacfe162418adcd25ca8af8"
      # se precisar: DATABASE_URL, etc.
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/healthz"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 20s
