apiVersion: v1
kind: Secret
metadata:
  name: roasbot-secrets
type: Opaque
stringData:
  # Tokens de ingest (separe por vírgula se tiver múltiplos)
  INGEST_TOKENS: "COLOQUE_SEU_TOKEN_AQUI"

  # Coloque aqui APENAS variáveis sensíveis (ex.: DB, tokens de API)
  # DATABASE_URL: "file:./prisma/dev.db"       # se usar SQLite no pod
  # TELEGRAM_BOT_TOKEN: "xxxx:yyyy"            # se um dia precisar
